using System.Text;

namespace ErCharExport;

public static class UnrealScriptGenerator
{
    public static string Generate(string characterId, Path fbx, Path textureDir, string textureQuality)
    {
        string assetRoot = $"/Game/EldenRingCharacters/{characterId}";
        var script = new StringBuilder();
        script.AppendLine("# Generated by er-char-export.");
        script.AppendLine("import os");
        script.AppendLine("import unreal");
        script.AppendLine();
        script.AppendLine($"CHARACTER_ID = {Py(characterId)}");
        script.AppendLine($"FBX_PATH = r{Py(fbx.FullName)}");
        script.AppendLine($"TEXTURE_DIR = r{Py(textureDir.FullName)}");
        script.AppendLine($"ASSET_ROOT = {Py(assetRoot)}");
        script.AppendLine();
        script.AppendLine("""
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
editor_asset_lib = unreal.EditorAssetLibrary

def ensure_dir(path):
    if not editor_asset_lib.does_directory_exist(path):
        editor_asset_lib.make_directory(path)

def import_one(filename, destination):
    task = unreal.AssetImportTask()
    task.filename = filename
    task.destination_path = destination
    task.automated = True
    task.save = True
    task.replace_existing = True
    asset_tools.import_asset_tasks([task])
    return list(task.imported_object_paths)

def import_fbx():
    return import_one(FBX_PATH, ASSET_ROOT + "/Mesh")

def import_textures():
    texture_dest = ASSET_ROOT + "/Textures"
    ensure_dir(texture_dest)
    imported = {}
    if not os.path.isdir(TEXTURE_DIR):
        unreal.log_warning("Texture directory does not exist: " + TEXTURE_DIR)
        return imported
    for name in os.listdir(TEXTURE_DIR):
        if not name.lower().endswith(".dds"):
            continue
        paths = import_one(os.path.join(TEXTURE_DIR, name), texture_dest)
        if not paths:
            continue
        asset = unreal.load_asset(paths[0])
        lower = name.lower()
        if asset:
            if lower.endswith("_n.dds") or lower.endswith("_n_l.dds"):
                asset.set_editor_property("srgb", False)
                asset.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_NORMALMAP)
            elif lower.endswith(("_m.dds", "_m_l.dds", "_v.dds", "_v_l.dds", "_1m.dds", "_1m_l.dds")):
                asset.set_editor_property("srgb", False)
                asset.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_MASKS)
            else:
                asset.set_editor_property("srgb", True)
            asset.modify()
            imported[os.path.splitext(name)[0].lower()] = asset
    return imported

def choose_group(name):
    n = name.lower()
    if "weapon" in n:
        return "weapon"
    if "hair" in n or "fur" in n:
        return "fur"
    return "body"

def create_material(name, textures):
    mat_dest = ASSET_ROOT + "/Materials"
    ensure_dir(mat_dest)
    material = asset_tools.create_asset(name, mat_dest, unreal.Material, unreal.MaterialFactoryNew())
    if not material:
        material = unreal.load_asset(mat_dest + "/" + name)
    if not material:
        unreal.log_warning("Could not create material: " + name)
        return None

    buckets = {}
    for tex_name, texture in textures.items():
        if choose_group(tex_name) != name.replace("M_", ""):
            continue
        if tex_name.endswith("_a") or tex_name.endswith("_a_l"):
            buckets["base"] = texture
        elif tex_name.endswith("_n") or tex_name.endswith("_n_l"):
            buckets["normal"] = texture
        elif tex_name.endswith("_em") or tex_name.endswith("_em_l"):
            buckets["emissive"] = texture
        elif tex_name.endswith("_m") or tex_name.endswith("_m_l"):
            buckets["metallic"] = texture

    x = -500
    if "base" in buckets:
        node = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionTextureSample, x, -200)
        node.texture = buckets["base"]
        unreal.MaterialEditingLibrary.connect_material_property(node, "RGB", unreal.MaterialProperty.MP_BASE_COLOR)
    if "normal" in buckets:
        node = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionTextureSample, x, 100)
        node.texture = buckets["normal"]
        unreal.MaterialEditingLibrary.connect_material_property(node, "RGB", unreal.MaterialProperty.MP_NORMAL)
    if "emissive" in buckets:
        node = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionTextureSample, x, 400)
        node.texture = buckets["emissive"]
        unreal.MaterialEditingLibrary.connect_material_property(node, "RGB", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    if "metallic" in buckets:
        node = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionTextureSample, x, 700)
        node.texture = buckets["metallic"]
        unreal.MaterialEditingLibrary.connect_material_property(node, "R", unreal.MaterialProperty.MP_METALLIC)

    unreal.MaterialEditingLibrary.layout_material_expressions(material)
    unreal.MaterialEditingLibrary.recompile_material(material)
    editor_asset_lib.save_loaded_asset(material)
    return material

def assign_materials(mesh_paths, materials):
    loaded_meshes = [unreal.load_asset(path) for path in mesh_paths]
    skeletal_meshes = [asset for asset in loaded_meshes if isinstance(asset, unreal.SkeletalMesh)]
    if not skeletal_meshes:
        unreal.log_warning("No skeletal mesh asset found after FBX import.")
        return
    mesh = skeletal_meshes[0]
    slots = mesh.get_editor_property("materials")
    for index, slot in enumerate(slots):
        slot_name = str(slot.material_slot_name).lower()
        chosen = materials.get("body")
        if "weapon" in slot_name:
            chosen = materials.get("weapon", chosen)
        elif "fur" in slot_name or "hair" in slot_name or "default" in slot_name:
            chosen = materials.get("fur", chosen)
        if chosen:
            mesh.set_material(index, chosen)
    mesh.modify()
    editor_asset_lib.save_loaded_asset(mesh)

ensure_dir(ASSET_ROOT)
fbx_assets = import_fbx()
textures = import_textures()
materials = {
    "body": create_material("M_body", textures),
    "fur": create_material("M_fur", textures),
    "weapon": create_material("M_weapon", textures),
}
assign_materials(fbx_assets, {k: v for k, v in materials.items() if v})
unreal.log("Imported " + CHARACTER_ID + " with heuristic materials.")
""");
        script.AppendLine($"# Texture quality used by export package: {textureQuality}");
        return script.ToString();
    }

    private static string Py(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}

